# Generated by Django 6.0.2 on 2026-03-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('duration', models.CharField(help_text='e.g. June 2023 - Aug 2023', max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(help_text='Link to hosting image', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
