# Generated by Django 6.0.2 on 2026-03-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_achievement_certification_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Programming Languages', 'Programming Languages'), ('Frameworks', 'Frameworks'), ('Databases', 'Databases'), ('Tools/Platforms', 'Tools/Platforms'), ('Soft Skills', 'Soft Skills'), ('Other', 'Other')], default='Programming Languages', max_length=50),
        ),
    ]
