# Generated by Django 6.0.2 on 2026-03-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='technologies',
            field=models.CharField(blank=True, help_text='Comma separated tech, e.g. React, Node', max_length=200, null=True),
        ),
    ]
