# Generated by Django 6.0.2 on 2026-03-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_internship_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='certificate_link',
            field=models.URLField(blank=True, help_text='Link to completion certificate', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='offer_letter_link',
            field=models.URLField(blank=True, help_text='Link to offer letter', max_length=500, null=True),
        ),
    ]
