# Generated by Django 6.0.1 on 2026-03-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_internship_certificate_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, help_text='GitHub repository URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_live',
            field=models.BooleanField(default=True, help_text='Check if the project is currently live'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, help_text='Live project URL', max_length=500, null=True),
        ),
    ]
