# Generated by Django 6.0.1 on 2026-03-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_project_github_link_project_is_live_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, help_text='Date for sorting (newest first)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='Link to hosting image', max_length=500, null=True),
        ),
    ]
