# Generated by Django 6.0.1 on 2026-03-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_project_order_project_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('duration', models.CharField(help_text='e.g. June 2023 - Aug 2023', max_length=100)),
                ('description', models.TextField()),
                ('technologies', models.CharField(blank=True, help_text='Comma separated tech, e.g. React, Node', max_length=200, null=True)),
                ('certificate_link', models.URLField(blank=True, help_text='Link to completion certificate', max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
