# Generated by Django 6.0.1 on 2026-03-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='order',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='order',
        ),
        migrations.RemoveField(
            model_name='education',
            name='order',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='order',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='order',
        ),
        migrations.RemoveField(
            model_name='training',
            name='order',
        ),
        migrations.AddField(
            model_name='education',
            name='date',
            field=models.DateField(blank=True, help_text='Completion date for sorting (newest first)', null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='date',
            field=models.DateField(blank=True, help_text='Completion date for sorting (newest first)', null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='date',
            field=models.DateField(blank=True, help_text='Date added (for sorting)', null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateField(blank=True, help_text='Completion date for sorting (newest first)', null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='date',
            field=models.DateField(blank=True, help_text='Date for sorting (newest first)', null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='date',
            field=models.DateField(blank=True, help_text='Completion date for sorting (newest first)', null=True),
        ),
    ]
